update

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,6 +1,6 @@
 # This is a basic workflow to help you get started with Actions
 
-name: First Workflow
+name: CI
 
 # Controls when the workflow will run
 on:
@@ -11,7 +11,7 @@ on:
 # A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
   # This workflow contains a single job called "build"
-  dev:
+  frontend_build:
     # The type of runner that the job will run on
     runs-on: ubuntu-latest
 
@@ -30,7 +30,7 @@ jobs:
           echo Add other actions to build,
           echo test, and deploy your project.
 
-  staging:
+  mock_server_build:
     # The type of runner that the job will run on
     runs-on: ubuntu-latest
 
@@ -49,14 +49,58 @@ jobs:
           echo Add other actions to build,
           echo test, and deploy your project.
           
-      - name: Try to fail
-        run: exit 1
-        
-      - name: Prevent merge
-        if: failure()
+#       - name: Try to fail
+#         run: exit 1
+
+
+  frontend_tests:
+    #hat the job will run on
+    runs-on: ubuntu-latest
+    needs : [frontend_build , mock_server_build]
+
+    # Steps represent a sequence of tasks that will be executed as part of the job
+    steps:
+      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
+      - uses: actions/checkout@v3
+
+      # Runs a single command using the runners shell
+      - name: Unit Tests
+        run: echo Hello, world!
+
+      # Runs a set of commands using the runners shell
+      - name: Integration Tests
         run: |
-          # Replace with your command to prevent the merge
-          git merge --abort
+          echo Add other actions to build,
+          echo test, and deploy your project.
+          
+
+  deploy-dev:
+    
+    runs-on: ubuntu-latest
+    needs : frontend_tests
+    
+    steps:
+      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
+      - uses: actions/checkout@v3
+
+      # Runs a single command using the runners shell
+      - name: Unit Tests
+        run: echo Hello, world!
+        
+        
+  deploy-prod:
+    
+    runs-on: ubuntu-latest
+    needs : deploy-dev
+    
+    steps:
+      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
+      - uses: actions/checkout@v3
+
+      # Runs a single command using the runners shell
+      - name: Unit Tests
+        run: echo Hello, world!
+
           
           
           
